#!/usr/bin/env bash

set -e
set -u

dotnet build MusicalGuide/MusicalGuide.csproj -c Release --output ./out

versionize

# Build again to get correct version number in assembly
dotnet build MusicalGuide/MusicalGuide.csproj -c Release --output ./out
git push --follow-tags

VERSION=$(versionize inspect)
cat << EOF > repository.json
[
  {
    "Author": "YF",
    "Name": "Musical Guide",
    "InternalName": "MusicalGuide",
    "AssemblyVersion": "$VERSION",
    "Description": "Provides real first person view to see your character, and adjusts camera distance based on game conditions (e.g. close in camera when you begin crafting, maximum distance when combat begins or you enter an instanced area)\n\n/mguide to open configuration window.",
    "ApplicableVersion": "any",
    "RepoUrl": "https://github.com/Sidiousious/musical-guide",
    "Tags": [
      "Camera"
    ],
    "DalamudApiLevel": 14,
    "LoadPriority": 0,
    "DownloadCount": 69,
    "IconUrl": "https://yfplugins.kinkop.eu/musical-guide.png",
    "Punchline": "Enhanced camera distance control and first-person experience.",
    "IsHide": "False",
    "IsTestingExclusive": "False",
    "DownloadLinkInstall": "https://yfplugins.kinkop.eu/musical-guide/$VERSION.zip",
    "DownloadLinkTesting": "https://yfplugins.kinkop.eu/musical-guide/$VERSION.zip",
    "DownloadLinkUpdate": "https://yfplugins.kinkop.eu/musical-guide/$VERSION.zip"
  }
]
EOF

s3cmd -c ~/.s3cfg-kinkop put out/MusicalGuide/latest.zip s3://yfplugins/musical-guide/$VERSION.zip
s3cmd -c ~/.s3cfg-kinkop put repository.json s3://yfplugins/musical-guide/repository.json
